# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"trim_cterm": "00_readproc.ipynb"}

modules = ["readproc.py"]

doc_url = "https://fastai.github.io/indel_analysis/"

git_url = "https://github.com/fastai/indel_analysis/tree/master/"

def custom_doc_links(name): return None
