# AUTOGENERATED! DO NOT EDIT! File to edit: 00_readproc.ipynb (unless otherwise specified).

__all__ = ['trim_cterm']

# Cell
import re
from pathlib import Path


def trim_cterm(inputFile, outputFile, motifToTrim):
    with open(inputFile, 'r') as inputFH:
        with open(outputFile,'w') as outputFH:
            i = 0
            for line in inputFH:
                i += 1
                if i%2 ==1: outputFH.write(line)
                else:
                    line = re.sub(motifToTrim, '', line)
                    #line += '\n'
                    outputFH.write(line)